### ISSUE TITLE
Creating Git Research Page

### ISSUE THREAD

**Issue by harunerkurt** [bounswe/bounswe2022group1#24]
Git research should be done and Git research page should be edited.

**Comment by kadirgokhann** [comment]
Is that page https://github.com/bounswe/bounswe2022group1/wiki/Favorite-Github-Repositories ? Or you mean onather research page?

**Comment by egetaga** [comment]
Instead of editing Favorite Github Repositories wiki, we should create a new wiki solely for Git research.

**Comment by egetaga** [comment]
I summarized my work in my [personal issue](https://github.com/bounswe/bounswe2022group1/issues/45): 
I changed the name of the previous empty About Git wiki to [A brief information about Git](https://github.com/bounswe/bounswe2022group1/wiki/A-brief-information-about-Git#how-to-use-git), since the previous name was not descriptive. Also I added 4 sections which summarize the essential properties of git. The sections are:

>[Git](https://github.com/bounswe/bounswe2022group1/wiki/A-brief-information-about-Git#git)
>[Why are Version Control Systems Useful?](https://github.com/bounswe/bounswe2022group1/wiki/A-brief-information->about-Git#why-are-version-control-systems-useful)
>[How to use Git?](https://github.com/bounswe/bounswe2022group1/wiki/A-brief-information-about-Git#how-to-use-git)
>[Resources](https://github.com/bounswe/bounswe2022group1/wiki/A-brief-information-about-Git#resources)
>Also I edited the home page to include the wiki. Done my work and closing this issue now.

Other team members may also add/edit the wiki page.

**Comment by harunerkurt** [comment]
Updating Git commands and Adding new git commands
Arranging and Tabulating commands
Adding differences between Git and GitHub
Adding GitGub definition
