### ISSUE TITLE
Customizing the labels

### ISSUE THREAD

**Issue by elxif** [bounswe/bounswe2022group1#5]
We should create new labels according to our project needs. I started by creating priority labels.

**Comment by omerozdemir1** [comment]
### Following 4 labels are added

- Priority-Critical
- Type-Defect
- Type-Enhancement
- Type-Review
- Type-Task

### Name of following labels are changed.

- High Priority --> Priority-High
- Medium Priority --> Priority-Medium
- Low Priority --> Priority-Low

**Comment by efekankavalci** [comment]
I want to point out two things:
* I think the format 'Priority: Critical' is more clear than 'Priority-Critical'. 
* I think status labels can prove to be useful, thus added several of them.  But, I think we should take everyone's opinion, maybe on a meeting, since they would not work well if everyone does not feel okay about them. Here is a useful resource about labels: https://github.com/Relequestual/sensible-github-labels

**Comment by harunerkurt** [comment]
[Duplicate](https://github.com/bounswe/bounswe2022group1/issues/19)
Labels are created and checked. A new issue has been opened about making the labels better.
