### ISSUE TITLE
Backend: Cors problem

### ISSUE THREAD

**Issue by kadirgokhann** [bounswe/bounswe2022group1#730]
**Issue Description:**

I'm using axios to get data from the endpoints. While getting the data, i am getting "cors" error for some url's. The cors configuration for some path may be done, but for some not. Could you check please?
https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework

**Tasks to Do:**

- [ ] configure the cors settings

Task Deadline: 20.12.2022

Reviewer: @kadirgokhann

Review Deadline: 20.12.2022

**Comment by egetaga** [comment]
I think you may have backend unrelated problem. Because, we've already enabled cors, as in your stack overflow link. On top of that, all postman requests work fine. Also, the android app works fine. So, it would be nice if you can check there is some other problem. 

It is very very unlikely that there is a problem with our settings. I checked twice.

**Comment by kadirgokhann** [comment]
I realized that its reason can be django. When i use "\" at the end of the url, there is no problem. If i dont use, i see the cors problem. Thank you @egetaga.

-> Solved.
