### ISSUE TITLE
Frontend: Resource, upvote

### ISSUE THREAD

**Issue by ecesrkn** [bounswe/bounswe2022group1#815]
**Issue Description:** Upvote functionality works, but it needs to be a clickable button and a counter box instead of a regular button and text box.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/43001709/209498364-e95a5368-7712-4ac2-8d49-ac7e16f41516.png">

Add a description of the issue

**Tasks to Do:**

- [x] select an icon for the upvote
- [x] update the view

*Task Deadline:* 26.12.2022 18.00

*Final Situation:*
<img width="190" alt="image" src="https://user-images.githubusercontent.com/43001709/209499877-5c5104b8-7cfd-491b-86c5-1cfa11c1a558.png">
 I am open to any placement and icon suggestions. This improvement corresponds to this [commit](https://github.com/bounswe/bounswe2022group1/commit/9fa0cbd1b0f00f89233ec9aaf918f4444c1f4234)

*Reviewer:*   @hseyyidkaplan 

*Review Deadline:* 26.12.2022 18.00

**Comment by hseyyidkaplan** [comment]
I checked this newly added feature and test it with different scenarios. I works smoothly. Pretty good work Ece, helath to your hands 💮

**I have a recommendation:** _when a member clicks to `upvote` button more than once, it is good to not reflect on a page because it is already counted as a vote._
