### ISSUE TITLE
Class Diagram: Student, Lecturer

### ISSUE THREAD

**Issue by mstfatay** [bounswe/bounswe2022group1#92]
We should decide attributes and methods of Student and Lecturer classes thinking in detail. Lecturer is inherited from Student. Therefore, we should be more careful about which class will own which attribute or method.

**Comment by egetaga** [comment]
On our meeting with the team, we decided on the following points related to Student and Lecturer classes: 

- Lecturer extends Student class, so every lecturer is also a student. 
- That means, only teaching related operations and fields shall be added to the lecturer. 
- Lecturer shall have a reputation, courses, statistics and rating as her primary fields. 
- Lecturer shall be able to modify, add or delete one of her courses. 
- Lecturer shall be able to create a poll. 
- All these decisions are taken based on the project requirements.

**Comment by egetaga** [comment]
According to the decisions taken by the team summarized on this [comment](https://github.com/bounswe/bounswe2022group1/issues/92#issuecomment-1088439012), I prepared a **Lecturer** class diagram as follows: 

- It has courses, rating,  statistics, reputation fields. 
- It has create_poll, create_course, get_courses, delete_course, retrieve_statistics and edit_course operations. 
- For the statistics, I have realized that I we need another class to represent statistics information and on discussion with @ecesrkn  and @mstfatay, we have decided to create a diagram for **Statistics** class. 
<img width="455" alt="Screen Shot 2022-04-05 at 11 41 19" src="https://user-images.githubusercontent.com/42147612/161717628-3fa211fc-ba89-44e8-b40b-e0d334823d25.png">

**Lecturer** needs further review, since it is one of the most important classes in our project.

**Comment by efekankavalci** [comment]
I specifically reviewed the **Lecturer** part again since @egetaga pointed out, I have noticed the lack of a method to upload content to the course, I have added a method such as "uploadContent(course_id: int, content_type: text)" and added an association line with the Content abstract data type. We can keep it if you approve it as well.

**Comment by mstfatay** [comment]
According to the discussion we did in our meeting, I created this student class diagram. Student is actually a loged in user. Therefore, there are attributes about authentication like username and password. Moreover, there are objects like achievements, courses and notes as attributes. We should create classes for those objects too. 


The diagram I created is as the following;

![student](https://user-images.githubusercontent.com/46002371/161844090-28bafa08-5211-48b3-91c0-ad6f0e63d4ee.png)

**Comment by ecesrkn** [comment]
Thanks to you all, your work looks great. There are only two missing parts if you haven't left them on purpose.

- [ ] in Lectures, the method `edit_course` doesn't have either parameter variable name or parameter data type. 
- [ ]  same as above, in Student, the method `create_subject_on_forum` doesn't have either parameter variable name or parameter data type.

**Comment by egetaga** [comment]
As I reviewed Ece's comment, in this phase of the work, it is well possible that the method parameters or names are not specified. It is not always possible to dwell onto details of these work. So, I am closing the issue, since I believe we reached our goal of the issue.
